language: android

jdk:
  - oraclejdk8
#  - oraclejdk7
#  - openjdk7
  - openjdk8

android:
  components:
    - build-tools-19.1.0
    - android-15


env:
  - TARGET=build
  - TARGET=test

script: ./gradlew $TARGET


matrix:
  exclude:
    - jdk: oraclejdk7
      env: TARGET=buildSwing
    - jdk: openjdk7
      env: TARGET=buildSwing
