language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7


env:
  - TARGET=build
  - TARGET=test

script: ./gradlew $TARGET


matrix:
  exclude:
    - jdk: oraclejdk7
      env: TARGET=buildSwing
    - jdk: openjdk7
      env: TARGET=buildSwing
