language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7


env:
  - TARGET=runUnitTests
  - TARGET=buildDedicatedServer
  - TARGET=buildSwing
# - TARGET=runAutosimTests

script: ANT_OPTS="-Xmx2048m" ant -buildfile ./build.ant $TARGET
