language: android
sudo: false

jdk:
  - oraclejdk8

android:
  components:
    - build-tools-19.1.0
    - android-15

before_install:
  - mkdir -p $HOME/.gradle/caches/
  - mkdir -p $HOME/.gradle/wrapper/
  - mkdir -p $HOME/dist

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/dist

before_script:
  - sudo service postgresql stop || true
  - sudo service mysql stop || true
  - sudo service memcached stop || true
  - sudo service bootlogd stop || true
  - sudo service elasticsearch stop || true
  - sudo service mongodb stop || true
  - sudo service neo4j stop || true
  - sudo service cassandra stop || true
  - sudo service riak stop || true
  - sudo service rsync stop || true
  - sudo service x11-common stop || true

script: GRADLE_OPTS="-Xmx2048m" ./gradlew $TARGET

env:
  # Only compile and build basic jars
  - TARGET="assemble" CACHE="1"
  - TARGET=":jsettlers.main.android:build"

  # Run single test targets
  - TARGET=":jsettlers.logic:test:unitTest --info"
  - TARGET=":jsettlers.common:test --info"
  - TARGET=":jsettlers.network:test --info"
  - TARGET=":jsettlers.logic:test:aiDifficultiesIT --info"
  - TARGET=":jsettlers.logic:test:autoReplayIT --info"
  - TARGET=":jsettlers.logic:test:replayValidationIT --info"
    
  # Test release generation
  - TARGET="release"

script: ./gradlew $TARGET; if [ "$CACHE" ]; then cp build/distributions/*.zip $HOME/dist; fi
