language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7


env:
  - TARGET=server.buildDedicatedServer
  - TARGET=swing.buildSwing
# - TARGET=runUnitTests
# - TARGET=runAutosimTests

script: ANT_OPTS="-Xmx2048m" ant -buildfile ./build.ant $TARGET
