language: android

jdk:
  - oraclejdk8
#  - oraclejdk7
#  - openjdk7
  - openjdk8

android:
  components:
    - build-tools-19.1.0
    - android-15


env:
  # Only compile and build basic jars
  - TARGET=assemble
  # This includes all tests
  - TARGET=build

script: ./gradlew $TARGET


matrix:
  exclude:
    - jdk: oraclejdk7
      env: TARGET=buildSwing
    - jdk: openjdk7
      env: TARGET=buildSwing
