language: android

jdk:
  - oraclejdk8
# Most of our build tasks except Android depend on 1.8
#  - oraclejdk7
#  - openjdk7
#  - openjdk8

android:
  components:
    - build-tools-19.1.0
    - android-15

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - sudo service postgresql stop || true
  - sudo service mysql stop || true
  - sudo service memcached stop || true
  - sudo service bootlogd stop || true
  - sudo service elasticsearch stop || true
  - sudo service mongodb stop || true
  - sudo service neo4j stop || true
  - sudo service cassandra stop || true
  - sudo service riak stop || true
  - sudo service rsync stop || true
  - sudo service x11-common stop || true

script: GRADLE_OPTS="-Xmx2048m" ./gradlew $TARGET

env:
  # Only compile and build basic jars
  - TARGET=assemble
  - TARGET=:jsettlers.main.android:build
  # This includes all tests
  #- TARGET=build
  # Run single test targets
  - TARGET=:jsettlers.logic:unitTest --info
  - TARGET=:jsettlers.logic:integrationTest --info
  - TARGET=:jsettlers.common:test --info
  - TARGET=:jsettlers.network:test --info

script: ./gradlew $TARGET


matrix:
  exclude:
    # assemble builds the swing projects. They cannot be built using JDK 1.7
    - jdk: oraclejdk7
      env: TARGET=assemble
    - jdk: openjdk7
      env: TARGET=assemble
