language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

script:
  - ANT_OPTS="-Xmx2048m" ant -buildfile ./build.ant runUnitTests
  - ANT_OPTS="-Xmx2048m" ant -buildfile ./build.ant runAutoReplayIT
  - ANT_OPTS="-Xmx2048m" ant -buildfile ./build.ant buildDedicatedServer
  - ANT_OPTS="-Xmx2048m" ant -buildfile ./build.ant buildSwing use oraclejdk8
  - ANT_OPTS="-Xmx2048m" ant -buildfile ./build.ant runAiDifficultiesIT
  - ANT_OPTS="-Xmx2048m" ant -buildfile ./build.ant runReplayValidationIT
